Implement domain layer
TeachMeMoreCode/TMMCBlog pull request #2
Opened 2017-01-08 04:53 UTC by timreimherr

When I changed the branch name it messed up the pull request, and now the first pull request is closed. So, I opened this request. 

Why did you say to make the method in the UIConverter class a static method? Forgot to change it to that and just remembered now, but I will change it to a static. 

I worked on having the BlogPost Controller use the new Domain Layer class and UIConverter class in creating a new post, thus, in order to get the project to build, I ended up persisting all the changes necessary to the View. But now it builds and I can see the website. I'm not sure if I set up the dependencies correctly...

2017-01-10 23:08 UTC, wojonet commented
@timreimherr UIConverter should be static because there's no advantage to having multiple instances of the method that does the conversion.

Everything else looks fine for now. At some point we should sit down and go through the project.

2017-01-10 23:08 UTC, wojonet requested changes

2017-01-10 23:08 UTC, wojonet commented on Blog/GamingGuruBlog.Web/GamingGuruBlog.Web/UIConverter.cs
> +    public class UIConverter
All this class should do is convert a viewmodel to a domain model and visa versa.

2017-01-10 23:08 UTC, wojonet commented on Blog/GamingGuruBlog.Web/GamingGuruBlog.Web/UIConverter.cs
> +        {
This work should be performed in the controller.

2017-01-17 14:27 UTC, timreimherr commented on Blog/GamingGuruBlog.Web/GamingGuruBlog.Web/UIConverter.cs
> +    public class UIConverter
@wojonet , I made these changes and commited them. 
Okay, I may have over done it but I'm not sure. When a BlogPostVM is turned to a BlogPost a lot items are created in the DB and then associated with that BlogPost. So, this is what is happening in the conversion and at the end it returns a BlogPost with all the associations. Is this correct?

2017-01-17 15:42 UTC, timreimherr commented
@wojonet 
Okay, I may have over done it, but I'm not sure. When a BlogPostVM is converted to a BlogPost there are items in the BPVM that need to created in the DB in order for them to be associated with the BlogPost that is returned. So that is what the converter class is doing. 

Is that correct?

2017-01-22 21:50 UTC, wojonet commented
Yeah I think you're getting it for the most part.....we'll meet soon and go over it, but  I think you have the basic idea. Nice work 👍

2017-01-22 21:50 UTC, merged